services:
  amialive:
    container_name: amialive
    image: ghcr.io/xstar97/amialive:latest
    restart: unless-stopped
    ports:
      - 6969
    healthcheck:
      test: curl --fail http://localhost:${PORT}/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - PORT=6969
    labels:
      - caddy=amialive.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 6969}}"
networks:
  default:
    name: caddy_net
    external: true
