x-healthcheck: &healthcheck
  test: ["CMD", "wget", "-qO-", "http://localhost:6969/healthz >/dev/null || exit 1"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  amialive:
    container_name: amialive
    image: ghcr.io/xstar97/amialive:0.0.2@sha256:c7a3f2f8c93a76ab2cdf525c99b99a88710109d8699b4969a97103929605946f
    restart: unless-stopped
    ports:
      - 6969
    #healthcheck: *healthcheck
    environment:
      - PORT=6969
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amialive.rule=Host(`amialive.${BASE_DOMAIN}`)"
      - "traefik.http.services.amialive.loadbalancer.server.port=6969"
      - "traefik.http.routers.amialive.entrypoints=websecure"
      - "traefik.http.routers.amialive.tls=true"
      - "traefik.http.routers.amialive.tls.certResolver=cf"
      - "traefik.http.routers.amialive.middlewares=error-pages-middleware"
networks:
  default:
    name: internal
    external: true
