services:
  amialive:
    container_name: amialive
    image: ghcr.io/xstar97/amialive:latest
    restart: unless-stopped
    ports:
      - 6969
    environment:
      - PORT=6969
    labels:
      - caddy=amialive.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 6969}}"
networks:
  default:
    name: caddy_net
    external: true
