services:
  amialive:
    container_name: amialive
    image: ghcr.io/xstar97/amialive:latest
    restart: unless-stopped
    ports:
      - 6969
    environment:
      - PORT=6969
networks:
  default:
    name: caddy_net
    external: true
