x-healthcheck: &healthcheck
  test: ["CMD", "wget", "-qO-", "http://localhost:6969/healthz >/dev/null || exit 1"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  amialive:
    container_name: amialive
    image: ghcr.io/xstar97/amialive:latest
    restart: unless-stopped
    ports:
      - 6969
    healthcheck: *healthcheck
    environment:
      - PORT=6969
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amialive.rule=Host(`amialive.${BASE_DOMAIN}`)"
      - "traefik.http.services.amialive.loadbalancer.server.port=6969" 
networks:
  default:
    name: internal
    external: true
