services:
  gotify:
    image: ghcr.io/gotify/server:2.8.0
    container_name: gotify
    restart: on-failure
    ports:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:$GOTIFY_SERVER_PORT/health || exit 1"]
      interval: 60s # Check every 60 seconds
      timeout: 10s  # Timeout after 10 seconds
      retries: 3    # Retry 3 times before marking as unhealthy
      start_period: 30s # Give it 30 seconds to start initially
    volumes:
      - /home/xstar97/docker/data/gotify/data:/app/data
    environment:
      GOTIFY_SERVER_PORT: 8080
    labels:
      - caddy.enable=false
      - homepage.group=Core
      - homepage.name=Gotify
      - homepage.icon=gotify.png
      - homepage.href=${HP_HREF}
      - homepage.widget.type=gotify
      - homepage.widget.url=${HP_WIDGET_URL}
      - homepage.widget.key=${HP_KEY}
      - homepage.description=Alert service
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  default:
    name: caddy_net
    external: true
