services:
  gotify:
    image: ghcr.io/gotify/server:2.8.0
    container_name: gotify
    ports:
      - 8082:80
    volumes:
      - /home/xstar97/docker/gotify/data:/app/data
    labels:
      - caddy.enable=false
      - homepage.group=Core
      - homepage.name=Gotify
      - homepage.icon=gotify.png
      - homepage.href=${HP_HREF}
      - homepage.widget.type=gotify
      - homepage.widget.url=${HP_WIDGET_URL}
      - homepage.widget.key=${HP_KEY}
      - homepage.description=Alert service
      - wud.tag.include=^\d+\.\d+\.\d+$$
    restart: on-failure
