services:
  code-server:
    restart: always
    image: ghcr.io/coder/code-server:4.105.1
    container_name: code
    ports:
      - 8083:8080
    volumes:
      - $/home/$USER/docker/code:/home/coder/.config
      - $/home/$USER/docker:/config
    labels:
      - caddy.enable=false
      - homepage.group=Core
      - homepage.name=Code Server
      # - homepage.href=http://seb.local:8082
      - homepage.description=editor software
      - wud.tag.include=^\d+\.\d+\.\d+$$
