services:
  code-server:
    image: ghcr.io/coder/code-server:4.108.2
    container_name: code
    restart: on-failure
    ports:
      - 8083:8080
    volumes:
      - /home/xstar97/docker/code:/home/coder/.config
      - /home/xstar97/docker:/config
    labels:
      - caddy.enable=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
