x-healthcheck: &healthcheck
  test: curl -f http://localhost:8080/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  code-server:
    image: ghcr.io/coder/code-server:4.108.2
    container_name: code
    restart: on-failure
    ports:
      - 8080
    # healthcheck: *healthcheck
    volumes:
      - /home/xstar97/docker/data/code:/home/coder/.config
      - /home/xstar97/docker:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.${BASE_DOMAIN}`)"
      - "traefik.http.services.code.loadbalancer.server.port=8080"
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls=true"
      - "traefik.http.routers.code.tls.certResolver=cf"
      - "traefik.http.routers.code.middlewares=error-pages-middleware"
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  default:
    name: internal
    external: true
