services:
  code-server:
    image: ghcr.io/coder/code-server:4.108.2
    container_name: code
    restart: on-failure
    ports:
      - 8080
    volumes:
      - /home/xstar97/docker/data/code:/home/coder/.config
      - /home/xstar97/docker:/config
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - caddy=code.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 8080}}"
networks:
  default:
    name: caddy_net
    external: true
