x-healthcheck: &healthcheck
  disable: true
  test:
    ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  wol:
    image: ghcr.io/trugamr/wol:0.1.0
    container_name: wol
    command: serve
    network_mode: host  # Uses host network
    restart: on-failure
    # healthcheck: *healthcheck
    environment:
      WOL_CONFIG: |
        machines:
          - name: wife-gaming-pc
            mac: "${GAMING_PC_W_MAC}"
            ip: "${GAMING_PC_W_IP}"
        server:
          listen: ":7777"
        ping:
          privileged: false
    labels:
      - "traefik.enable=true"  # Enable routing
      - "traefik.http.routers.wol.rule=Host(`wol.${BASE_DOMAIN}`)"  # This is the domain you're routing for
      - "traefik.http.routers.wol.service=wol-service"  # Define the custom service name
      - "traefik.http.services.wol-service.loadbalancer.server.scheme=http"  # Set the scheme (http or https)
      - "traefik.http.services.wol-service.loadbalancer.server.port=7777"  # Specify port 7777
      - "traefik.http.services.wol-service.loadbalancer.server.address=${SEB_IP}"  # Direct to specific IP address
      - wud.tag.include=^\d+\.\d+\.\d+$
networks:
  default:
    name: internal
    external: true