x-healthcheck: &healthcheck
  disable: true
  test:
    ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  wol:
    image: ghcr.io/trugamr/wol:0.1.0
    container_name: wol
    command: serve
    network_mode: host  # Uses host network
    restart: on-failure
    # healthcheck: *healthcheck
    environment:
      WOL_CONFIG: |
        machines:
          - name: wife-gaming-pc
            mac: "${GAMING_PC_W_MAC}"
            ip: "${GAMING_PC_W_IP}"
        server:
          listen: ":7777"
        ping:
          privileged: false
    labels:
      - "traefik.enable=true"  # Enable routing
      - "traefik.http.routers.wol.rule=Host(`wol.${BASE_DOMAIN}`)"
      - "traefik.http.services.wol.loadbalancer.server.port=7777"  # Expose port directly
      - wud.tag.include=^\d+\.\d+\.\d+$
networks:
  default:
    name: internal
    external: true