services:
  wol:
    image: ghcr.io/trugamr/wol:0.1.0
    command: serve
    network_mode: host
    container_name: wol
    env_file:
      - ./wol.secrets.enc.env
    volumes:
      - ./config.yaml:/etc/wol/config.yaml
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
