services:
  wol:
    image: ghcr.io/trugamr/wol:0.1.0
    container_name: wol
    command: serve
    network_mode: host
    restart: on-failure
    healthcheck:
      disable: true
      test: curl --fail http://localhost:7777 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      WOL_CONFIG: |
        machines:
          - name: wife-gaming-pc
            mac: "${GAMING_PC_W_MAC}"
            ip: "${GAMING_PC_W_IP}"
        server:
          listen: ":7777"
        ping:
          privileged: false
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$
      - caddy=wol.${BASE_DOMAIN}
      - caddy.reverse_proxy="http://seb.local:7777"
networks:
  default:
    name: caddy_net
    external: true
