x-healthcheck: &healthcheck
  test: ["CMD", "/dozzle", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  dozzle:
    image: amir20/dozzle:v9.0.3
    container_name: dozzle
    restart: on-failure
    environment:
      - DOZZLE_ADDR=:8080
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_NO_ANALYTICS=true
    ports:
      - 8080
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: dozzle.${BASE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
networks:
  default:
    name: caddy_net
    external: true
