services:
  bedrockconnect:
    container_name: bedrockconnect
    image: pugmatt/bedrock-connect:1.65
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    network_mode: host
    volumes:
      - /home/xstar97/docker/data/bedrockconnect/config/custom_servers.json:/app/custom_servers.json
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
