x-healthcheck: &healthcheck
  disable: true
  test:
    ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  rompatcherjs:
    container_name: rompatcherjs
    image: ghcr.io/xstar97/rompatcherjs:v3.2.1
    ports:
      - 3314
    # healthcheck: *healthcheck
    environment:
      - SERVER_PORT=3314
    labels:
      - caddy=rompatcherjs.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 3314}}"
networks:
  default:
    name: caddy_net
    external: true
