x-healthcheck: &healthcheck
  test: curl -f http://localhost:3314/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  rompatcherjs:
    container_name: rompatcherjs
    image: ghcr.io/xstar97/rompatcherjs:v3.2.1
    ports:
      - 3314
    healthcheck: *healthcheck
    environment:
      - SERVER_PORT=3314
      - HELLO=${HELLO}
    labels:
      - caddy=rompatcherjs.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 3314}}"
networks:
  default:
    name: caddy_net
    external: true
