services:
  rompatcherjs:
    container_name: rompatcherjs
    image: ghcr.io/xstar97/rompatcherjs:v3.2.1
    ports:
      - 3314
    healthcheck:
      test: curl --fail http://localhost:${SERVER_PORT}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - SERVER_PORT=3314
    labels:
      - caddy=rompatcherjs.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 3314}}"
networks:
  default:
    name: caddy_net
    external: true
