services:
  wud:
    image: ghcr.io/getwud/wud:8.1.1
    container_name: wud
    restart: on-failure
    ports:
      - 3000
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}
      - caddy=wud.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 3000}}"
networks:
  default:
    name: caddy_net
    external: true
