x-healthcheck: &healthcheck
  disable: true
  test:
    ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  wud:
    image: ghcr.io/getwud/wud:8.1.1
    container_name: wud
    restart: on-failure
    environment:
      - WUD_SERVER_PORT=3000
    ports:
      - 3000
    # healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`wud.${BASE_DOMAIN}`)"
      - "traefik.http.services.wud.loadbalancer.server.port=3000" 
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}
networks:
  default:
    name: internal
    external: true
