services:
  caddy:
    image: caddy:2.10.2-alpine
    container_name: caddy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /home/xstar97/docker/caddy/conf:/etc/caddy
      - /home/xstar97/docker/caddy/data:/data
      - /home/xstar97/docker/caddy/config:/config
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-alpine$$
