x-healthcheck: &healthcheck
  test: curl -f http://localhost/healthz || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  caddy:
    build: .
    image: caddy-cloudflare:2.10.2
    container_name: caddy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xstar97/docker/data/caddy/conf:/etc/caddy
      - /home/xstar97/docker/data/caddy/data:/data
      - /home/xstar97/docker/data/caddy/config:/config
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/docker.Caddyfile
      - CADDY_INGRESS_NETWORKS=caddy_net
      - BASE_DOMAIN=${BASE_DOMAIN}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CADDY_DOCKER_PROXY_SERVICE_TASKS=false
    networks:
      - caddy_net
networks:
  caddy_net:
    external: true
