services:
  caddy:
    build: .
    image: caddy-cloudflare:2.10.2
    container_name: caddy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /home/xstar97/docker/data/caddy/conf:/etc/caddy
      - /home/xstar97/docker/data/caddy/data:/data
      - /home/xstar97/docker/data/caddy/config:/config
    networks:
      - caddy_net
networks:
  caddy_net:
    external: true
