services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.9.0
    container_name: homepage
    restart: on-failure
    ports:
      - 3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/healthcheck", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xstar97/docker/data/homepage/config:/app/config
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - caddy=homepage.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 3000}}"
networks:
  default:
    name: caddy_net
    external: true
