x-healthcheck: &healthcheck
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.0
    container_name: homepage
    restart: on-failure
    ports:
      - 3000
    healthcheck: *healthcheck
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xstar97/docker/data/homepage/config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${BASE_DOMAIN}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certResolver=cf"
      - "traefik.http.routers.homepage.middlewares=error-pages-middleware"
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  default:
    name: internal
    external: true
