services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.6
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    volumes:
      - /home/xstar97/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    labels:
      - caddy.enable=false
      - wud.tag.include=^\d+\.\d+\.\d+$$