services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2
    container_name: dockerproxy
    ports:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+$$
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.6
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    volumes:
      - /home/xstar97/docker/homepage/config:/app/config
    labels:
      - caddy.enable=false
      - wud.tag.include=^\d+\.\d+\.\d+$$