services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik
    restart: on-failure
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - BASE_DOMAIN=${BASE_DOMAIN}
    command:
      - --certificatesresolvers.cf.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cf.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesresolvers.cf.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.dnsChallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cf.acme.storage=/certs/acme.json
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=cf
      - --entrypoints.websecure.http.tls.domains[0].main=*.${BASE_DOMAIN}
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - "--log.level=DEBUG"  # Set log level to DEBUG
      - "--accesslog=true"   # Enable access logs to stdout
      - "--api.insecure=true"  # Enable the Traefik dashboard without authentication
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xstar97/docker/data/traefik/certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${BASE_DOMAIN}`)"  # Expose dashboard
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"  # Dashboard listens on port 8080
      - "traefik.http.routers.traefik.entrypoints=websecure"  # Serve the dashboard over HTTPS
      - "traefik.http.routers.traefik.tls=true"  # Enable TLS for the dashboard
      - "traefik.http.routers.traefik.tls.certResolver=cf"  # Use Let's Encrypt for TLS
    networks:
      - internal
networks:
  internal:
    external: true
