services:
  gatus:
    restart: always
    image: ghcr.io/twin/gatus:v5.34.0
    container_name: gatus
    ports:
      - 8888:8080
    volumes:
      - /home/xstar97/docker/gatus/config:/config
      - /home/xstar97/docker/gatus/data:/data
    environment:
      - GATUS_CONFIG_PATH=/config
    labels:
      - caddy.enable=false
      - homepage.group=Core
      - homepage.name=Gatus
      - homepage.icon=gatus.png
      - homepage.href=${HP_HREF}
      - homepage.widget.type=gatus
      - homepage.widget.url=${HP_WIDGET_URL}
      - homepage.description=Status Page
