services:
  gatus:
    restart: always
    image: ghcr.io/twin/gatus:v5.30.0
    container_name: gatus
    ports:
      - 8080:8080
    volumes:
      - ~/docker/gatus/config:/config
      - ~/docker/gatus/data:/data
    environment:
      - GATUS_CONFIG_PATH=/config
