services:
  gatus:
    image: ghcr.io/twin/gatus:v5.34.0
    container_name: gatus
    restart: on-failure
    environment:
      - GATUS_CONFIG_PATH=/config
    ports:
      - 8080
    volumes:
      - /home/xstar97/docker/data/gatus/config:/config
      - /home/xstar97/docker/data/gatus/data:/data
    labels:
      - caddy.enable=false
      - homepage.group=Core
      - homepage.name=Gatus
      - homepage.icon=gatus.png
      - homepage.href=${HP_HREF}
      - homepage.widget.type=gatus
      - homepage.widget.url=${HP_WIDGET_URL}
      - homepage.description=Status Page
networks:
  default:
    name: caddy_net
    external: true
