x-healthcheck: &healthcheck
  test: curl -f http://localhost:8080/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  gatus:
    image: ghcr.io/twin/gatus:v5.34.0
    container_name: gatus
    restart: on-failure
    environment:
      - GATUS_CONFIG_PATH=/config
    ports:
      - 8080
    # healthcheck: *healthcheck
    volumes:
      - /home/xstar97/docker/data/gatus/config:/config
      - /home/xstar97/docker/data/gatus/data:/data
    labels:
      - homepage.group=Core
      - homepage.name=Gatus
      - homepage.icon=gatus.png
      - homepage.href=${HP_HREF}
      - homepage.widget.type=gatus
      - homepage.widget.url=http://gatus:8080
      - homepage.description=Status Page
      - caddy=gatus.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 8080}}"
networks:
  default:
    name: caddy_net
    external: true
