x-healthcheck: &healthcheck
  # wget and curl do not exist since 1.3.2
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  prunemate:
    image: anoniemerd/prunemate:1.3.2
    container_name: prunemate
    restart: on-failure
    environment:
      - PRUNEMATE_TIME_24H=true
    ports:
      - 8080
    # healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xstar97/docker/data/prunemate/config:/config
      - /home/xstar97/docker/data/prunemate/logs:/var/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${BASE_DOMAIN}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=8080" 
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  default:
    name: internal
    external: true
