x-healthcheck: &healthcheck
  disable: true
  test:
    ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  prunemate:
    image: anoniemerd/prunemate:1.3.2
    container_name: prunemate
    restart: on-failure
    environment:
      - PRUNEMATE_TIME_24H=true
    ports:
      - 8080
    # healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xstar97/docker/data/prunemate/config:/config
      - /home/xstar97/docker/data/prunemate/logs:/var/log
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - caddy=prunemate.${BASE_DOMAIN}
      - caddy.reverse_proxy="{{upstreams 8080}}"
networks:
  default:
    name: caddy_net
    external: true
