services:
  prunemate:
    image: anoniemerd/prunemate:1.3.2
    container_name: prunemate
    volumes:
      - /home/xstar97/docker/prunemate/config:/config
      - /home/xstar97/docker/prunemate/logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:3000
    environment:
      - PRUNEMATE_TIME_24H=true
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}
