services:
  prunemate:
    image: anoniemerd/prunemate:1.3.2
    container_name: prunemate
    restart: on-failure
    environment:
      - PRUNEMATE_TIME_24H=true
    ports:
      - 7676:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xstar97/docker/prunemate/config:/config
      - /home/xstar97/docker/prunemate/logs:/var/log
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
